openapi: 3.0.0
info:
  version: 1.0.0
  title: My Product Project CRUD
  description: My Product Project Application API
servers:
- url: http://localhost:3000/
  description: local server
paths:
  /customer:
    get: 
      responses:
        200:
          description: customer get
          content:
            application/json:
              schema:
                type: string